Meesterproef/Meesterproef/Models/ErrorViewModel.cs
using System;

namespace Meesterproef.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Meesterproef/Meesterproef/Models/PartijModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Meesterproef.Models
{
    public class PartijModel
    {
        public int Id { get; set; }
        public string Orde { get; set; }
        public string VoledigeNaam { get; set; }
        
    }
}

Meesterproef/Meesterproef/Models/UitslagModel.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
 using Microsoft.AspNetCore.Mvc.Rendering;

 namespace Meesterproef.Models
{
    public class UitslagModel
    {
        public int Id { get; set; }
        public string Naam { get; set; }
        public DateTime Datum { get; set; }
        public int ZetelAantal { get; set; }

        public List<VerkiezingModel> Verkiezingen { get; set; }
    }
}

Meesterproef/Meesterproef/Models/VerkiezingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Meesterproef.Models
{
    public class VerkiezingModel
    {
        public int Stemmen { get; set; }
        public decimal Percentage { get; set; }
        public int Zetels { get; set; }
        public string OrdeTrekker { get; set; }
        public PartijModel Partij { get; set; }
    }
}

Meesterproef/Meesterproef/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FactorysLogic;
using InterfacesLogic;
using LogicaLaag;
using Microsoft.AspNetCore.Mvc;
using Meesterproef.Models;

namespace Meesterproef.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            string aanpasData = PartijFactory.MaakPartijAan(3, "", "OrdeTestPartij").PartijAanpassen();
            return View();
        }
    }
}

Meesterproef/Meesterproef/Controllers/PartijController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactorysLogic;
using Meesterproef.Models;
using Microsoft.AspNetCore.Mvc;
using InterfacesLogic;

namespace Meesterproef.Controllers
{
    public class PartijController : Controller
    {
        public IActionResult PartijAanpassen()
        {
            List<IPartij> partijen = PartijFactory.MaakPartijContainerAan().HaalAllePartijenOp();

            ViewBag.partijen = partijen;

            
            return View();
        }

        [HttpPost]
        public IActionResult PartijAanpassen(PartijModel partijModel, int partijId)
        {
            List<IPartij> partijen = PartijFactory.MaakPartijContainerAan().HaalAllePartijenOp();

            ViewBag.partijen = partijen;

            string aanpasData = PartijFactory.MaakPartijAan(partijId, partijModel.Orde,partijModel.VoledigeNaam).PartijAanpassen();

            ViewBag.AanpasData = aanpasData;

            return View();
        }

        public IActionResult PartijToevoegen()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PartijToevoegen(PartijModel partijModel)
        {

            IPartij iPartij = PartijFactory.MaakPartijAan(partijModel.Id, partijModel.Orde, partijModel.VoledigeNaam);
            string partijUitkomst = PartijFactory.MaakPartijContainerAan().MaakPartijAan(iPartij);

            ViewBag.PartijData = partijUitkomst;

            return View();
        }
    }
}

Meesterproef/Meesterproef/Controllers/UitslagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FactorysLogic;
using InterfacesLogic;
using LogicaLaag;
using Meesterproef.Models;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Bcpg;

namespace Meesterproef.Controllers
{

    public class UitslagController : Controller
    {
        

        public IActionResult ToevoegenUitslag()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ToevoegenUitslag(UitslagModel uitslagModel)
        {
            IUitslag uitslag = UitslagFactory.MaakUitslag(uitslagModel.Id, uitslagModel.Naam, uitslagModel.Datum, uitslagModel.ZetelAantal);

            ViewBag.UitslagData = UitslagFactory.MaakUitslagContainer().MaakUitslagAan(uitslag);
            //voegt uitslag toe

            return View();
        }

        public IActionResult UitslagTonen()
        {
            List<IUitslag> uitslagen = UitslagFactory.MaakUitslagContainer().HaalAlleUitslagenOp();

            ViewBag.Uitslagen = uitslagen;
            //Haal alle uitslagen op

            return View();
        }

        [HttpPost]
        public IActionResult UitslagTonen(VerkiezingModel verkiezingModel, int uitslagId, string uitslagNaam, string orde, string volledigeNaam, string ordeTrekker, string submit,string clearCoalitie)
        {

            ICoalitie iCoalitie = CoalitieFactory.MaakLegeCoalitie();


            if (iCoalitie.verkiezingen.Count > 0)
            {

            }


            //party id en uitslag id de verkiezing ophalen


            //haalt alle uitslagen op om in het drop down menu te zetten
            List<IUitslag> uitslagen = UitslagFactory.MaakUitslagContainer().HaalAlleUitslagenOp();

            ViewBag.Uitslagen = uitslagen;


            //haalt een uitslag op
            IUitslag IUitslag = UitslagFactory.MaakUitslagContainer().HaalUitslagOpMetNaam(uitslagNaam.ToString());

            //Haal de alle data op van de gewenste uitslag met de naam van de uitslag
            IUitslag uitslag = UitslagFactory.MaakUitslagContainer().HaalAlleDataVanUitslagOp(IUitslag);

            if (submit != null)
            {
                //haalt de geselecteerde verkiezing op
                IVerkiezing iVerkiezing =
                    VerkiezingFactory.MaakVerkiezingContainer().HaalVerkiezingOp(Convert.ToInt32(submit));

                iCoalitie.verkiezingen.Add(iVerkiezing);
            }

            if (clearCoalitie == "clear")
            {
                iCoalitie.verkiezingen.Clear();
            }

            
            ViewBag.Coalitie = iCoalitie.verkiezingen;
            ViewBag.Uitslag = uitslag;
            ViewBag.Verkiezingen = uitslag.Verkiezingen;

            return View();
        }

        //geef de button als value het id van de verkiezing

        public IActionResult UitslagAanpassen()
        {
            List<IUitslag> uitslagen = UitslagFactory.MaakUitslagContainer().HaalAlleUitslagenOp();

            ViewBag.Uitslagen = uitslagen;

            return View();
        }

        [HttpPost]
        public IActionResult UitslagAanpassen(UitslagModel uitslagModel, string uitslagId)
        {
            List<IUitslag> uitslagen = UitslagFactory.MaakUitslagContainer().HaalAlleUitslagenOp();

            ViewBag.Uitslagen = uitslagen;


            string aanpasData = UitslagFactory.MaakUitslag(Convert.ToInt32(uitslagId), uitslagModel.Naam, uitslagModel.Datum, uitslagModel.ZetelAantal).UitslagAanpassen();

            ViewBag.AanpasData = aanpasData;

            return View();
        }
    }

}

Meesterproef/Meesterproef/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Meesterproef/Meesterproef/Views/Partij/PartijAanpassen.cshtml
@using InterfacesLogic
@model PartijModel
@{
    ViewData["Title"] = "PartijAanpassen";
}

<h2>PartijAanpassen</h2>


<form asp-action="PartijAanpassen" asp-controller="Partij" id="UitslagFrom">

    <p>Selecteer de Partij die u aan wilt passen:</p>



    @{
        List<SelectListItem> listItems = new List<SelectListItem>();

        @foreach (IPartij item in ViewBag.partijen)
        {

            listItems.Add(new SelectListItem
            {
                Text = item.VoledigeNaam,
                Value = item.Id.ToString()
            });
        }

    }


    @Html.DropDownList("partijId", listItems)


    <p>Orde afkorting: <input asp-for="Orde" type="text" /></p>
    <p>Volledige naam: <input asp-for="VoledigeNaam" type="text" /></p>
    

    <p>@ViewBag.AanpasData</p>

    <p><input type="submit" name="Ophalen" text="Veranderen" /></p>
</form>

Meesterproef/Meesterproef/Views/Partij/PartijToevoegen.cshtml
@model PartijModel

@{
    ViewData["Title"] = "PartijToevoegen";
}

<h2>PartijToevoegen</h2>

<form asp-action="PartijToevoegen" asp-controller="Partij">
    <p>Afkorting: <input asp-for="Orde" type="text" /></p>
    <p>Volledige Naam: <input asp-for="VoledigeNaam" type="text" /></p>

    <p><input type="submit" name="Create" /></p>

    <p>@ViewBag.PartijData</p>

</form>

Meesterproef/Meesterproef/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meesterproef</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Meesterproef</div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Uitslag" asp-action="UitslagTonen">Uitslagen</a></li>
                    <li><a asp-area="" asp-controller="Uitslag" asp-action="ToevoegenUitslag">Uitslag Toevoegen</a></li>
                    <li><a asp-area="" asp-controller="Uitslag" asp-action="UitslagAanpassen">Uitslag Aanpassen</a></li>
                    <li><a asp-area="" asp-controller="Partij" asp-action="PartijToevoegen">Partij Toevoegen</a></li>
                    <li><a asp-area="" asp-controller="Partij" asp-action="PartijAanpassen">Partij Aanpassen</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Meesterproef</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Meesterproef/Meesterproef/Views/Uitslag/ToevoegenUitslag.cshtml
@model UitslagModel
@{
    ViewData["Title"] = "ToevoegenUitslag";
}

<h2>ToevoegenUitslag</h2>

<form asp-action="ToevoegenUitslag" asp-controller="Uitslag">
    <p>Naam: <input asp-for="Naam" type="text" /></p>
    <p>Datum: <input asp-for="Datum" type="date" /></p>
    <p>Aantal zetels: <input asp-for="ZetelAantal" type="number" /></p>

    <p><input type="submit" name="Create" /></p>

    <p>@ViewBag.UitslagData</p>

</form>

Meesterproef/Meesterproef/Views/Uitslag/UitslagAanpassen.cshtml
@using InterfacesLogic
@model UitslagModel

@{
    ViewData["Title"] = "UitslagAanpassen";
}

<h2>UitslagAanpassen</h2>

<form asp-action="UitslagAanpassen" asp-controller="Uitslag" id="UitslagFrom">

    <p>Selecteer de Uitslag die u wilt zien:</p>



    @{
        List<SelectListItem> listItems = new List<SelectListItem>();

        @foreach (IUitslag item in ViewBag.Uitslagen)
        {

            listItems.Add(new SelectListItem
            {
                Text = item.Naam,
                Value = item.Id.ToString()
            });
        }

    }


    @Html.DropDownList("uitslagId",listItems)

    
    <p><input asp-for="Naam" type="hidden" name="uitslagId"/></p>
    <p>Naam: <input asp-for="Naam" type="text" /></p>
    <p>Datum: <input asp-for="Datum" type="date" /></p>
    <p>Aantal zetels: <input asp-for="ZetelAantal" type="number" /></p>
    
    <p>@ViewBag.AanpasData</p>

    <p><input type="submit" name="Ophalen" text="Veranderen"/></p>
</form>

Meesterproef/Meesterproef/Views/Uitslag/UitslagTonen.cshtml
@using InterfacesLogic
@using Microsoft.EntityFrameworkCore.Internal
@model VerkiezingModel

@{
    ViewData["Title"] = "UitslagTonen";
}

<h2>UitslagTonen</h2>

<form asp-action="UitslagTonen" asp-controller="Uitslag" id="UitslagFrom">

    <p>Selecteer de Uitslag die u wilt zien:</p>



    @{
        List<SelectListItem> listItems = new List<SelectListItem>();

        @foreach (IUitslag item in ViewBag.Uitslagen)
        {

            listItems.Add(new SelectListItem
            {
                Text = item.Naam,
                Value = item.Naam
            });
        }

    }


    @Html.DropDownList("uitslagNaam", listItems)


    <p><input type="submit" name="s" text="Ophalen" value="HaalVerkiezingenOp" /></p>

    @if (ViewBag.Verkiezingen != null)
    {


        <table class="table">
            <thead>
                <tr>

                    <th>
                        Orde
                    </th>
                    <th>
                        Voledige naam
                    </th>
                    <th>
                        Orde trekker
                    </th>
                    <th>
                        Stemmen
                    </th>
                    <th>
                        Percentage
                    </th>
                    <th>
                        Zetels
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (IVerkiezing item in ViewBag.Verkiezingen)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Partij.Orde)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Partij.VoledigeNaam)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrdeTrekker)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Stemmen)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Percentage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Zetels)
                        </td>
                        <td>


                            <input asp-for="Stemmen" type="hidden" value="@item.Stemmen" />
                            <input asp-for="Percentage" type="hidden" value="@item.Percentage" />
                            <input asp-for="Zetels" type="hidden" value="@item.Zetels" />



                            <input type="hidden" value="@item.Partij.Id" name="uitslagId" />
                            <input type="hidden" value="@item.Partij.Orde" name="orde" />
                            <input type="hidden" value="@item.Partij.VoledigeNaam" name="volledigeNaam" />
                            <input type="hidden" value="@item.OrdeTrekker" name="ordeTrekker" />

                            @*@Html.ActionLink("Uitslag", "UitslagTonen",@item)*@

                            <input type="submit" name="submit" text="VoegToe" value="@item.Id" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    <p>Coalitie</p>

    @if (ViewBag.Coalitie != null)
    {
        <table class="table">
            <thead>
                <tr>

                    <th>
                        Orde
                    </th>
                    <th>
                        Voledige naam
                    </th>
                    <th>
                        Orde trekker
                    </th>
                    <th>
                        Stemmen
                    </th>
                    <th>
                        Percentage
                    </th>
                    <th>
                        Zetels
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (IVerkiezing verkiezing in ViewBag.Coalitie)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => verkiezing.Partij.Orde)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => verkiezing.Partij.VoledigeNaam)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => verkiezing.OrdeTrekker)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => verkiezing.Stemmen)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => verkiezing.Percentage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => verkiezing.Zetels)
                        </td>

                    </tr>
                }
            </tbody>
        </table>
        <input type="text" name="doesListHaveItems" text="items" value="@ViewBag.Coalitie" />
    }

    <input type="submit" name="clearCoalitie" text="VoegToe" value="clear" />

</form>

Meesterproef/Meesterproef/Views/Uitslag/asdfas.cshtml
@model IEnumerable<LogicaLaag.Uitslag>

@{
    ViewData["Title"] = "asdfas";
}

<h2>asdfas</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZetelAantal)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZetelAantal)
            </td>
            <td>
                <input type=""/>
                <button onclick="onClickFuntion()">toevoegen</button>
            </td>
        </tr>

    }
    </tbody>
</table>